version: '3.8'
services:
  service:
    build: ./app
    expose:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      - theatre-db
    volumes:
      - /app/static:/opt/app/static  

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./app/static:/opt/app/static:ro  
    depends_on:
      - service
    ports:
      - "80:80"


  theatre-db:
    image: postgres:latest
    container_name: postgres_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  database_dump.sql:
  configs:
  nginx.conf:
  static:
  
networks:
  default:
    driver: bridge